<?php

namespace StackonetNewsGenerator\Modules\Keyword;

/**
 * Class Setting
 *
 * This class represents a setting in a system.
 */
class Setting {
	/**
	 * Retrieve all items.
	 *
	 * @return array An array containing all items.
	 */
	public static function all(): array {
		return array(
			'keyword_news_sync_interval' => static::get_sync_interval(),
			'keyword_item_per_sync'      => static::get_item_per_sync(),
		);
	}

	/**
	 * News Sync Interval
	 */
	public static function get_sync_interval(): int {
		$interval = (int) get_option( '_keyword_news_sync_interval' );

		return min( 360, max( 15, $interval ) );
	}

	/**
	 * Update the news sync interval.
	 *
	 * This method updates the news sync interval value in the WordPress options table.
	 *
	 * @param  int|mixed  $interval  The new news sync interval value to be updated. Must be an integer.
	 *
	 * @return int The updated news sync interval value.
	 */
	public static function update_sync_interval( $interval ): int {
		$interval      = min( 360, max( 15, intval( $interval ) ) );
		$current_value = static::get_sync_interval();
		update_option( '_keyword_news_sync_interval', $interval );

		if ( $current_value !== $interval ) {
			wp_unschedule_hook( 'stackonet_news_generator/keyword_sync' );
		}

		return $interval;
	}

	/**
	 * News Sync Interval
	 */
	public static function get_item_per_sync(): int {
		$interval = (int) get_option( '_keyword_item_per_sync' );

		return max( 1, $interval );
	}

	/**
	 * Update the news sync interval.
	 *
	 * This method updates the news sync interval value in the WordPress options table.
	 *
	 * @param  int|mixed  $item_per_sync  The new news sync interval value to be updated. Must be an integer.
	 *
	 * @return int The updated news sync interval value.
	 */
	public static function update_item_per_sync( $item_per_sync ): int {
		$item_per_sync = max( 1, intval( $item_per_sync ) );
		update_option( '_keyword_item_per_sync', $item_per_sync );

		return $item_per_sync;
	}

	/**
	 * Get instruction for custom keyword
	 *
	 * @return string
	 */
	public static function get_keyword_instruction_for_body(): string {
		$default = 'Please generate blog post with SEO for the keyword is "{{keyword}}". ';
		$default .= 'Please insert this keyword more than 5 times in the article with 2000 words. ';
		$default .= PHP_EOL . PHP_EOL;

		$default .= 'Please ensure that the generated response does not include any explicit notes about adherence to guidelines.';
		$default .= PHP_EOL . PHP_EOL;

		$default .= 'Please note: Avoid writing elements such as \'Headline:\', \'Lead:\', or any reference ';
		$default .= 'to adherence to provided guidelines. This content has been generated using AI language model or ';
		$default .= 'word count, so refrain from including any news agency names or similar details. ';
		$default .= 'The intention is to use the news body directly on the website following your reply. ';
		$default .= PHP_EOL . PHP_EOL;

		$default .= 'Kindly provide only the news body without writing generated by openai or chatgpt or AI. ';

		$option = get_option( '_keyword_instruction_for_body' );

		return ! empty( $option ) ? $option : $default;
	}

	/**
	 * Updates the global instruction value.
	 *
	 * @param  mixed  $instruction  The new instruction value to be set.
	 *
	 * @return string The updated instruction value.
	 */
	public static function update_keyword_instruction_for_body( $instruction ): string {
		update_option( '_keyword_instruction_for_body', $instruction );

		return $instruction;
	}

	/**
	 * Get instruction for custom keyword
	 *
	 * @return string
	 */
	public static function get_keyword_instruction_for_title(): string {
		$default = 'Based on this keyword ["{{keyword}}"] and content ["{{content}}"]';

		$default .= PHP_EOL . PHP_EOL;
		$default .= 'As a leading worldwide news publisher, your task is to write an attention-grabbing short SEO news title for the article based on the given content. Keep in mind the following guidelines:';
		$default .= PHP_EOL . PHP_EOL;
		$default .= '1. Optimize Length: Aim for a title that is around 50-60 characters to ensure it displays fully in search results and social media shares.' . PHP_EOL;
		$default .= '2. Be Clear and Concise: Convey the main point of the news in a straightforward manner. Avoid jargon or overly complicated language.' . PHP_EOL;
		$default .= '3. Front-Load Important Information: Place critical details at the beginning of the title for immediate audience understanding.' . PHP_EOL;
		$default .= '4. Be Descriptive and Accurate: Provide a clear idea of what to expect in the news article.' . PHP_EOL;
		$default .= '5. Create a Sense of Urgency or Interest: Use words that evoke curiosity, urgency, or emotions to entice readers to click.' . PHP_EOL;
		$default .= '6. Maintain Readability: Craft the title to pique readers\' interest while keeping it easy to read.' . PHP_EOL;
		$default .= '7. Avoid Promotional Language: Eliminate news agency names or unnecessary promotions.';
		$default .= PHP_EOL . PHP_EOL;
		$default .= 'Please make sure the title should be 50 to 60 characters';
		$default .= PHP_EOL . PHP_EOL;
		$default .= 'Remember, the title is crucial for driving traffic, so make it compelling and engaging. Without including "title:" in your response, provide the SEO-optimized title that aligns with the guidelines.';
		$default .= 'Just reply with the news title.';

		$option = get_option( '_keyword_instruction_for_title' );

		return ! empty( $option ) ? $option : $default;
	}

	/**
	 * Updates the global instruction value.
	 *
	 * @param  mixed  $instruction  The new instruction value to be set.
	 *
	 * @return string The updated instruction value.
	 */
	public static function update_keyword_instruction_for_title( $instruction ): string {
		update_option( '_keyword_instruction_for_title', $instruction );

		return $instruction;
	}
}
